# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyrth', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Contrib', models.IntegerField(choices=[(1, 'Formateur'), (2, 'Sponsor'), (3, 'Partenaire Technique'), (4, 'Partenaire Financier'), (5, 'Mentor'), (6, 'Autre')], default=1)),
                ('Autres', models.TextField(blank=True)),
            ],
        ),
    ]
