# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-19 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyrth', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactContrib',
        ),
    ]
